In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences

sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'i am a good boy',
    'i am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [9]:
## define the vocabulary size
voc_size=10000

In [10]:
### One hot representation
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[5261, 2610, 7255, 5209],
 [5261, 2610, 7255, 7675],
 [5261, 1998, 7255, 9113],
 [2819, 3986, 4088, 18, 7478],
 [2819, 3986, 4088, 18, 5041],
 [5411, 5261, 5517, 7255, 509],
 [7901, 1541, 8861, 18]]

In [11]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np 

In [13]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5261 2610 7255 5209]
 [   0    0    0    0 5261 2610 7255 7675]
 [   0    0    0    0 5261 1998 7255 9113]
 [   0    0    0 2819 3986 4088   18 7478]
 [   0    0    0 2819 3986 4088   18 5041]
 [   0    0    0 5411 5261 5517 7255  509]
 [   0    0    0    0 7901 1541 8861   18]]


In [14]:
## Feature representation
dim=10

In [16]:
## create model

model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [17]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [18]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 155ms/step


array([[[ 0.04898126,  0.00301876,  0.04093683, -0.03124532,
          0.00100439,  0.01649359, -0.03797026,  0.04527355,
          0.03773368, -0.00114442],
        [ 0.04898126,  0.00301876,  0.04093683, -0.03124532,
          0.00100439,  0.01649359, -0.03797026,  0.04527355,
          0.03773368, -0.00114442],
        [ 0.04898126,  0.00301876,  0.04093683, -0.03124532,
          0.00100439,  0.01649359, -0.03797026,  0.04527355,
          0.03773368, -0.00114442],
        [ 0.04898126,  0.00301876,  0.04093683, -0.03124532,
          0.00100439,  0.01649359, -0.03797026,  0.04527355,
          0.03773368, -0.00114442],
        [ 0.01383973,  0.04544861, -0.01895607, -0.01044328,
         -0.01875314,  0.01859024,  0.00737593, -0.01123857,
          0.03578499,  0.02077464],
        [-0.03501792,  0.01729376,  0.03904418,  0.04077554,
          0.00227157, -0.03203354, -0.0316484 , -0.03302421,
          0.02911455, -0.02217838],
        [ 0.01972734, -0.04935158, -0.02568839, -0.0